[phases.setup]
aptPkgs = [
  "libsqlite3-0",
  "libsqlite3-dev",
  "libpango-1.0-0",
  "libpangocairo-1.0-0",
  "libpangoft2-1.0-0",
  "libgdk-pixbuf2.0-0",
  "libffi-dev",
  "shared-mime-info",
  "libcairo2",
  "libglib2.0-0",
  "libgobject-2.0-0",
  "libharfbuzz0b",
  "libfontconfig1",
  "fonts-dejavu-core"
]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["python3 manage.py collectstatic --noinput"]

[start]
cmd = "chmod +x release.sh && ./release.sh && gunicorn dental_clinic.wsgi --bind 0.0.0.0:$PORT --workers 2"
